# OCR.space API Key
OCR_SPACE_API_KEY = "K88544333088957"

[supabase]
SUPABASE_URL = "https://zonxlcgvjzibarsduajd.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvbnhsY2d2anppYmFyc2R1YWpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU4MTgyMjgsImV4cCI6MjA1MTM5NDIyOH0.MQO_j-JgWfbmZ_4s9Cndwc4ldmHl5uC9AgPwtdolnKo"
